import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from engine.rag_engine import RAGEngine

DATA = """
LIBRARY API REFERENCE DOCUMENTATION: RAGEngine

Function 1: chunk_text(text: str, max_words: int, overlap: int) -> List[str]
Splits the input string into sequential text chunks based on word count limits.
- Parameters:
  * text (str): The raw string document to be partitioned.
  * max_words (int): The maximum number of words allowed per chunk.
  * overlap (int): The number of shared trailing/leading words retained between adjacent sliding-window chunks.
- Significance: Overlap is critical because it preserves boundary context between consecutive chunks, preventing key sentences or semantic concepts from being truncated or severed in half across chunk breaks.

Function 2: retrieve(query: str, top_k: int = 3) -> List[Tuple[int, float, str]]
Executes a vector search over pre-indexed document chunks using TF-IDF vectorization and Cosine Similarity.
- Parameters:
  * query (str): The search query string submitted by the user.
  * top_k (int): Number of top matching chunks to retrieve (default is 3).
- Returns: A list of tuples containing (1-based source index, similarity score float, chunk text string) ordered by similarity score descending.

Function 3: ask(query: str) -> str
Orchestrates context retrieval and LLM completion via the Anthropic Claude API.
- Process: Retrieves top_k chunks, formats them as source context, and builds a strictly grounded system prompt.
- Returns: A string response generated by the LLM citing explicit sources like `[Source X]`. If no relevant context is found or if the retrieved chunks do not contain sufficient evidence to answer the query, `ask()` returns exactly: "I don't have that information."
"""

PERSONA = "a precise technical assistant explaining this library's API to a developer"

def main():
    print("=" * 70)
    print("USE CASE 5: CODE & API DOCUMENTATION ASSISTANT")
    print("=" * 70)

    engine = RAGEngine(doc_text=DATA, persona=PERSONA, max_words=80, overlap=20, top_k=3)

    queries = [
        "What does overlap do in chunk_text, and why does it matter?",
        "What does the ask() function return if nothing relevant is found?"
    ]

    for q in queries:
        print(f"\n[QUERY]: {q}")
        response = engine.ask(q)
        print(f"[RESPONSE]:\n{response}")
        print("-" * 50)

if __name__ == "__main__":
    main()
